name: CI-Windows
on:
  push:
    branches: [ '*' ]
    paths-ignore:         # Don't trigger on files that are updated by the CI
      - README.md
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run at 02:01 on the 3rd of each month
    - cron:  '1 2 3 * *'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: conda-incubator/setup-miniconda@main
        with:
          activate-environment: polsys_env
          python-version: 3.12
          auto-activate-base: false
          miniconda-version: "latest"
          auto-update-conda: true
          add-pip-as-python-dependency: true
      - shell: bash -l {0}
        run: |
          # Use conda to manage the building toolchain, but is now outdated
          # https://numpy.org/doc/stable/f2py/windows/index.html
          conda install m2w64-toolchain libpython
      - name: Build
        shell: bash -l {0}
        run: |
            # Ignore `pyproject.toml` to avoid conda/pip mix in numpy version            
            python -m pip install -v .  
      - name: Test
        shell: bash -l {0}
        run: |
            # force to use the installed package and not the one from the local repo.
            rm pypolsys/__init__.py
            python -m pypolsys.test

